# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, verbose_name='Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('money', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Money')),
                ('description', models.CharField(max_length=70, verbose_name='Description')),
                ('category', models.CharField(max_length=70, verbose_name='Category')),
                ('payment', models.CharField(max_length=70, verbose_name='Payment')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
