# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-12 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('money', models.DecimalField(decimal_places=2, max_digits=8)),
                ('kind', models.CharField(max_length=20)),
                ('which_target', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('basicdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.BasicData')),  # noqa: E501
                ('tx_op', models.DecimalField(decimal_places=2, max_digits=4)),
                ('brokerage', models.CharField(max_length=15)),
            ],
            bases=('investments.basicdata',),
        ),
        migrations.CreateModel(
            name='InvestmentDetails',
            fields=[
                ('basicdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.BasicData')),  # noqa: 501
                ('segment', models.CharField(max_length=10)),
                ('tx_or_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quant', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            bases=('investments.basicdata',),
        ),
    ]
