# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-04 14:45
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='basicdata_ptr',
        ),
        migrations.RemoveField(
            model_name='investmentdetails',
            name='basicdata_ptr',
        ),
        migrations.AddField(
            model_name='investment',
            name='basic_data',
            field=models.OneToOneField(default=uuid.uuid1, on_delete=django.db.models.deletion.CASCADE,
                                       primary_key=True, serialize=False, to='investments.BasicData'),
        ),
        migrations.AddField(
            model_name='investmentdetails',
            name='basic_data',
            field=models.OneToOneField(default=uuid.uuid1, on_delete=django.db.models.deletion.CASCADE,
                                       primary_key=True, serialize=False, to='investments.BasicData'),
        ),
    ]
