# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-04 15:05
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('investments', '0002_auto_20180804_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='basic_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                       to='investments.BasicData'),
        ),
        migrations.AlterField(
            model_name='investmentdetails',
            name='basic_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                       to='investments.BasicData'),
        ),
    ]
