# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_auto_20180804_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicdata',
            name='which_target',
        ),
        migrations.AddField(
            model_name='investmentdetails',
            name='which_target',
            field=models.CharField(default='---', max_length=20),
        ),
    ]
