# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_auto_20180920_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['-basic_data__date']},
        ),
        migrations.AlterModelOptions(
            name='investmentdetails',
            options={'ordering': ['-basic_data__date']},
        ),
        migrations.AlterField(
            model_name='investmentdetails',
            name='which_target',
            field=models.CharField(default='---', max_length=40),
        ),
    ]
