# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_auto_20180925_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentdetails',
            name='segment',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='investmentdetails',
            name='which_target',
            field=models.CharField(default='---', max_length=20),
        ),
    ]
