# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_auto_20180925_2117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvestmentDetails',
            new_name='OldInvestmentDetails',
        ),
    ]
