# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-01 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0011_auto_20180927_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newinvestment',
            name='kind',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='newinvestmentdetails',
            name='kind',
            field=models.CharField(max_length=35),
        ),
    ]
