# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-05 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0012_auto_20181001_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newinvestment',
            name='kind',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='newinvestmentdetails',
            name='kind',
            field=models.CharField(max_length=40),
        ),
    ]
