# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-06 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0013_auto_20181005_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newinvestment',
            name='kind',
            field=models.CharField(default='---', max_length=40),
        ),
        migrations.AlterField(
            model_name='newinvestmentdetails',
            name='kind',
            field=models.CharField(default='---', max_length=40),
        ),
        migrations.AlterField(
            model_name='newinvestmentdetails',
            name='quant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='newinvestmentdetails',
            name='segment',
            field=models.CharField(default='---', max_length=20),
        ),
        migrations.AlterField(
            model_name='newinvestmentdetails',
            name='tx_or_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
