# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-06 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0014_auto_20181006_1656'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewInvestment',
            new_name='OldNewInvestment',
        ),
        migrations.RenameModel(
            old_name='NewInvestmentDetails',
            new_name='OldNewInvestmentDetails',
        ),
    ]
