# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-06 19:18
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0015_auto_20181006_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # noqa
                ('tx_op', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('brokerage', models.CharField(max_length=15)),
                ('user_name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('money', models.DecimalField(decimal_places=2, max_digits=8)),
                ('kind', models.CharField(default='---', max_length=40)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='NewInvestmentDetails',
            fields=[
                ('newinvestment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.NewInvestment')),  # noqa
                ('which_target', models.CharField(default='---', max_length=20)),
                ('segment', models.CharField(default='---', max_length=20)),
                ('tx_or_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('quant', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
            bases=('investments.newinvestment',),
        ),
    ]
