# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-06 19:22
from __future__ import unicode_literals

from django.db import migrations


def forward_copy_src_to_dst(apps, schema_editor):
    source = apps.get_model('investments', 'OldNewInvestment')
    destination = apps.get_model('investments', 'NewInvestment')

    for src in source.objects.all():
        dst = destination(
            user_name=src.user_name,
            date=src.date,
            money=src.money,
            kind=src.kind,
            tx_op=src.tx_op,
            brokerage=src.brokerage
        )

        dst.save()


def backward_copy_dst_src(apps, schema_editor):
    destination = apps.get_model('investments', 'OldNewInvestment')
    source = apps.get_model('investments', 'NewInvestment')

    for src in source.objects.all():
        dst = destination(
            user_name=src.user_name,
            date=src.date,
            money=src.money,
            kind=src.kind,
            tx_op=src.tx_op,
            brokerage=src.brokerage
        )

        dst.save()


def forward_copy_dsrc_to_ddst(apps, schema_editor):
    source = apps.get_model('investments', 'OldNewInvestmentDetails')
    destination = apps.get_model('investments', 'NewInvestmentDetails')

    for src in source.objects.all():
        dst = destination(
            user_name=src.user_name,
            date=src.date,
            money=src.money * -1,
            kind=src.kind,
            tx_op=0.00,
            brokerage='unknown',
            which_target=src.which_target,
            segment=src.segment,
            tx_or_price=src.tx_or_price,
            quant=src.quant
        )

        dst.save()


def backward_copy_dsrc_to_ddst(apps, schema_editor):
    destination = apps.get_model('investments', 'OldNewInvestmentDetails')
    source = apps.get_model('investments', 'NewInvestmentDetails')

    for src in source.objects.all():
        dst = destination(
            user_name=src.user_name,
            date=src.date,
            money=src.money,
            kind=src.kind,
            which_target=src.which_target,
            segment=src.segment,
            tx_or_price=src.tx_or_price,
            quant=src.quant
        )

        dst.save()


class Migration(migrations.Migration):
    dependencies = [
        ('investments', '0016_newinvestment_newinvestmentdetails'),
    ]

    operations = [
        migrations.RunPython(forward_copy_src_to_dst, backward_copy_dst_src),
        migrations.RunPython(forward_copy_dsrc_to_ddst, backward_copy_dsrc_to_ddst)
    ]
