# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-20 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, verbose_name='Name')),
                ('date', models.DateField(auto_now=True, verbose_name='Date')),
                ('description', models.CharField(max_length=70, verbose_name='Description')),
                ('category', models.CharField(max_length=70, verbose_name='Category')),
                ('payment', models.CharField(max_length=70, verbose_name='Payment')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
