# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extract',
            name='money',
            field=models.FloatField(default=0.0, verbose_name='Money'),
        ),
        migrations.AlterField(
            model_name='extract',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
