# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170223_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extract',
            name='money',
            field=models.FloatField(default='00.00', verbose_name='Money'),
        ),
    ]
