# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170223_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extract',
            name='money',
            field=models.FloatField(default=0.0, verbose_name='Money'),
        ),
    ]
