# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170225_2044'),
        ('core', '0005_auto_20170223_1858'),
    ]

    operations = [
    ]
