# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20170228_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extract',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='extract',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Money'),
        ),
    ]
