# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-22 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170318_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extract',
            name='payment',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=70, verbose_name='Payment'),
        ),
    ]
