# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170622_1106'),
    ]

    database_operations = [
        migrations.AlterModelTable('Extract', 'bank_extract')
    ]

    state_operations = [
        migrations.DeleteModel('Extract')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
