# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-01-06 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170622_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extract',
            name='money',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Money'),
        ),
    ]
